### ISSUE TITLE
Nothing displays when there are no quotes to retrieve.

### ISSUE THREAD

**Issue by bendurston** [yoiksoft/kwot#11]
Right after the day ends, the vote page will be blank until at least two quotes have been written for that day.

Back end returns `204 no content` when there aren't enough quotes to display (i.e. no quotes for the day or no more new quotes to vote on).

**Comment by matootie** [comment]
This should be fixed... but I'm not 100% sure because I haven't tested. We'll see come 7pm EST tonight..

**Comment by matootie** [comment]
Fixed
